replicaCount: 1

image:
  repository: tahler/fortio
  tag: prometheus
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

resources:
  requests:
    cpu: 1000m
    memory: 100Mi
  limits  :
    cpu: 4000m
    memory: 100Mi

nodeSelector:
