---
apiVersion: v1
kind: Secret
metadata:
  name: mdb-secrets
type: Opaque
stringData:
  MONGODB_BACKUP_USER: backup
  MONGODB_BACKUP_PASSWORD: backup123456
  MONGODB_CLUSTER_ADMIN_USER: clusterAdmin
  MONGODB_CLUSTER_ADMIN_PASSWORD: clusterAdmin123456
  MONGODB_CLUSTER_MONITOR_USER: clusterMonitor
  MONGODB_CLUSTER_MONITOR_PASSWORD: clusterMonitor123456
  MONGODB_USER_ADMIN_USER: userAdmin
  MONGODB_USER_ADMIN_PASSWORD: userAdmin123456
  PMM_SERVER_USER: admin
  PMM_SERVER_PASSWORD: admin

---
apiVersion: psmdb.percona.com/v1-9-0
kind: PerconaServerMongoDB
metadata:
  name: mdb
  finalizers:
  - delete-psmdb-pvc
spec:
  crVersion: 1.9.0
  image: percona/percona-server-mongodb:4.4.6-8
  imagePullPolicy: Always
  allowUnsafeConfigurations: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: 4.4-recommended
    schedule: "0 2 * * *"
    setFCV: false
  secrets:
    users: mdb-secrets
  pmm:
    enabled: false
  replsets:
  - name: rs0
    size: 3
    storage:
      engine: wiredTiger
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    nodeSelector:
      role: exp-subject
    resources:
      limits:
        cpu: "4000m"
        memory: "4G"
      requests:
        cpu: "4000m"
        memory: "4G"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 100Mi
    livenessProbe:
      failureThreshold: 10
      initialDelaySeconds: 300
      periodSeconds: 30
      timeoutSeconds: 30
      startupDelaySeconds: 7200
  - name: rs1
    size: 3
    storage:
      engine: wiredTiger
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    nodeSelector:
      role: exp-subject
    resources:
      limits:
        cpu: "4000m"
        memory: "4G"
      requests:
        cpu: "4000m"
        memory: "4G"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 100Mi
    livenessProbe:
      failureThreshold: 10
      initialDelaySeconds: 300
      periodSeconds: 30
      timeoutSeconds: 30
      startupDelaySeconds: 7200
  sharding:
    enabled: true
    configsvrReplSet:
      size: 3
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      nodeSelector:
        role: exp-subject
      resources:
        limits:
          cpu: "2000m"
          memory: "1G"
        requests:
          cpu: "2000m"
          memory: "1G"
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 100Mi
      livenessProbe:
        failureThreshold: 10
        initialDelaySeconds: 300
        periodSeconds: 30
        timeoutSeconds: 30
        startupDelaySeconds: 7200
    mongos:
      size: 3
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      nodeSelector:
        role: exp-subject
      resources:
        limits:
          cpu: "4000m"
          memory: "4G"
        requests:
          cpu: "4000m"
          memory: "4G"
      expose:
        exposeType: ClusterIP
