apiVersion: apps/v1
kind: Deployment
metadata:
  name: d
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: d
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: d
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: d
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-0
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-0
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-0
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-0
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-1
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-1
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-1
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-2
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-2
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-2
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-0-0
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-0-0
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-0-0
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-0-0
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-0-1
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-0-1
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-0-1
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-0-1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-0-2
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-0-2
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-0-2
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-0-2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-1-0
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-1-0
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-1-0
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-1-0
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-1-1
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-1-1
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-1-1
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-1-1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-1-2
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-1-2
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-1-2
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-1-2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-2-0
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-2-0
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-2-0
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-2-0
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-2-1
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-2-1
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-2-1
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-2-1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-0-2-2
  labels:
{{ include "isotope-tree.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: svc-0-2-2
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        name: svc-0-2-2
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-2-2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mock-service
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
